default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: nuggets_development

test:
  <<: *default
  database: nuggets_test

production:
  <<: *default
  database: nuggets_production
